# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu14.04"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
  config.vm.hostname = "#{config.vm.box}-ruby2-#{Time.now.to_i}"
  config.vm.provision "file", source: "~/.ssh/github_id_rsa", destination: "/home/vagrant/.ssh/id_rsa"
  config.vm.provision "shell", inline: "chmod 600 /home/vagrant/.ssh/id_rsa"

  config.vm.provision "shell", inline: <<-SHELL
    sudo locale-gen ja_JP.UTF-8
    sudo timedatectl set-timezone Asia/Tokyo
    sudo apt-get update
    sudo add-apt-repository -y ppa:brightbox/ruby-ng
    sudo apt-get update -y
    sudo apt-get install ruby2.3 ruby2.3-dev git g++ -y
    sudo gem install bundler
    test -d dotfiles \
    || ( /usr/bin/git clone https://github.com/simeji/dotfiles.git \
    && /bin/bash dotfiles/setup.sh dotfiles \
    && /bin/bash dotfiles/setup.sh vimenv \
    )
  SHELL
end
