# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box = "maier/alpine-3.3-x86_64"
  config.vm.hostname = "alpline-3.3"

  config.vm.network "forwarded_port", guest: 80, host: 3000
  config.vm.network "forwarded_port", guest: 443, host: 3001

  config.vbguest.auto_update = false
  config.vbguest.no_remote = true
  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.provision "file", source: "repositories", destination: "/tmp/repositories"

  config.vm.provision "shell", inline: <<-SHELL
    sudo mv /tmp/repositories /etc/apk/repositories
    sudo apk update
    sudo apk add nginx
    sudo service nginx start
  SHELL
end
