# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
NGINX_VERSION = '1.11.3'

Vagrant.configure(2) do |config|
  config.vm.box = "maier/alpine-3.3-x86_64"
  config.vm.hostname = "alpline-3.3"

  config.vm.network "forwarded_port", guest: 80, host: 3000
  config.vm.network "forwarded_port", guest: 443, host: 3001

  config.vbguest.auto_update = false
  config.vbguest.no_remote = true
  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.provision "file", source: "repositories", destination: "/tmp/repositories"
  config.vm.provision "file", source: "nginx.conf", destination: "/tmp/nginx.conf"

  config.vm.provision "shell", inline: <<-SHELL
    sudo mv /tmp/repositories /etc/apk/repositories
    sudo apk update
    apk --update add pcre-dev openssl-dev \
    && apk add --virtual build-dependencies build-base curl \
    && curl -SLO http://nginx.org/download/nginx-#{NGINX_VERSION}.tar.gz \
    && tar xzvf nginx-#{NGINX_VERSION}.tar.gz \
    && cd nginx-#{NGINX_VERSION} \
    && ./configure \
         --with-http_ssl_module \
         --with-http_v2_module \
         --with-http_gzip_static_module \
         --prefix=/usr/share/nginx \
         --sbin-path=/usr/local/sbin/nginx \
         --conf-path=/etc/nginx/conf/nginx.conf \
         --pid-path=/var/run/nginx.pid \
         --http-log-path=/var/log/nginx/access.log \
         --error-log-path=/var/log/nginx/error.log \
    && make \
    && make install \
    && cd / \
    && apk del build-dependencies \
    && rm -rf \
      nginx-#{NGINX_VERSION} \
      nginx-#{NGINX_VERSION}.tar.gz \
      /var/cache/apk/*

    sudo mv /tmp/nginx.conf /etc/nginx/conf/nginx.conf
    sudo /usr/local/sbin/nginx -t  && sudo /usr/local/sbin/nginx -t 
  SHELL
end
